# nFPM configuration for the main algorand package
# Generates both .deb and .rpm from a single config
# Reference: https://nfpm.goreleaser.com/configuration/
#
# Required environment variables:
#   VERSION         - Package version (e.g., 4.5.0)
#   CHANNEL         - Release channel (stable, beta, nightly, dev)
#   PKG_NAME        - Package name: "algorand" for most channels, "algorand-beta" for beta
#   DEFAULTNETWORK  - Default genesis network (mainnet, betanet, devnet)
#   BINDIR          - Directory containing built binaries

name: ${PKG_NAME}
arch: ${GOARCH}
version: ${VERSION}
platform: linux

maintainer: Algorand developers <dev@algorand.com>
vendor: Algorand Inc.
homepage: https://www.algorand.com
license: AGPL-3.0-or-later
description: |
  Algorand node software.
  This package provides an implementation of the Algorand protocol.

# Package relationships
depends:
  - systemd
recommends:
  - unattended-upgrades
replaces:
  - algorand
  - algorand-beta
conflicts:
  - algorand
  - algorand-beta

contents:
  # Main binaries (expand: true required for env var expansion in src/dst)
  - src: ${BINDIR}/algocfg
    dst: /usr/bin/algocfg
    expand: true
    file_info:
      mode: 0755

  - src: ${BINDIR}/algod
    dst: /usr/bin/algod
    expand: true
    file_info:
      mode: 0755

  - src: ${BINDIR}/algoh
    dst: /usr/bin/algoh
    expand: true
    file_info:
      mode: 0755

  - src: ${BINDIR}/algokey
    dst: /usr/bin/algokey
    expand: true
    file_info:
      mode: 0755

  - src: ${BINDIR}/diagcfg
    dst: /usr/bin/diagcfg
    expand: true
    file_info:
      mode: 0755

  - src: ${BINDIR}/goal
    dst: /usr/bin/goal
    expand: true
    file_info:
      mode: 0755

  - src: ${BINDIR}/kmd
    dst: /usr/bin/kmd
    expand: true
    file_info:
      mode: 0755

  - src: ${BINDIR}/node_exporter
    dst: /usr/bin/node_exporter
    expand: true
    file_info:
      mode: 0755

  # Library files
  - src: ${BINDIR}/updater
    dst: /usr/lib/algorand/updater
    expand: true
    file_info:
      mode: 0755

  - src: scripts/find-nodes.sh
    dst: /usr/lib/algorand/find-nodes.sh
    file_info:
      mode: 0755

  # Configuration files
  - src: installer/config.json.example
    dst: /var/lib/algorand/config.json.example
    file_info:
      mode: 0644

  - src: installer/system.json
    dst: /var/lib/algorand/system.json
    type: config|noreplace
    file_info:
      mode: 0644

  # Genesis files - all networks
  - src: installer/genesis/mainnet/genesis.json
    dst: /var/lib/algorand/genesis/mainnet/genesis.json
    file_info:
      mode: 0644

  - src: installer/genesis/testnet/genesis.json
    dst: /var/lib/algorand/genesis/testnet/genesis.json
    file_info:
      mode: 0644

  - src: installer/genesis/betanet/genesis.json
    dst: /var/lib/algorand/genesis/betanet/genesis.json
    file_info:
      mode: 0644

  - src: installer/genesis/devnet/genesis.json
    dst: /var/lib/algorand/genesis/devnet/genesis.json
    file_info:
      mode: 0644

  - src: installer/genesis/alphanet/genesis.json
    dst: /var/lib/algorand/genesis/alphanet/genesis.json
    file_info:
      mode: 0644

  # Default genesis.json (channel-specific, set by DEFAULTNETWORK)
  - src: installer/genesis/${DEFAULTNETWORK}/genesis.json
    dst: /var/lib/algorand/genesis.json
    type: config|noreplace
    expand: true
    file_info:
      mode: 0644

  # Systemd service files
  - src: installer/algorand.service
    dst: /lib/systemd/system/algorand.service
    file_info:
      mode: 0644

  - src: installer/algorand@.service
    dst: /lib/systemd/system/algorand@.service
    file_info:
      mode: 0644

  # Data directory (empty, with correct permissions)
  - dst: /var/lib/algorand
    type: dir
    file_info:
      mode: 0775
      owner: algorand
      group: algorand

  # Debian copyright file (deb only, generated at build time)
  - src: .github/packaging/generated/copyright
    dst: /usr/share/doc/${PKG_NAME}/copyright
    expand: true
    packager: deb
    file_info:
      mode: 0644

  # DNF automatic update configuration (rpm only)
  - src: installer/rpm/algorand/0dnf-algorand-hourly.cron
    dst: /etc/cron.hourly/0dnf-algorand-hourly.cron
    type: config|noreplace
    packager: rpm
    file_info:
      mode: 0755

  - src: installer/rpm/algorand/dnf-cron-algorand.conf
    dst: /etc/dnf/dnf-cron-algorand.conf
    type: config|noreplace
    packager: rpm
    file_info:
      mode: 0644

  # Unattended upgrades configuration (deb only, generated at build time)
  - src: .github/packaging/generated/51algorand-upgrades
    dst: /etc/apt/apt.conf.d/51algorand-upgrades
    type: config|noreplace
    packager: deb
    file_info:
      mode: 0644

# Maintainer scripts (unified - detect deb vs rpm at runtime)
scripts:
  preinstall: .github/packaging/scripts/algorand-preinstall.sh
  postinstall: .github/packaging/scripts/algorand-postinstall.sh
  preremove: .github/packaging/scripts/algorand-preremove.sh
  postremove: .github/packaging/scripts/algorand-postremove.sh

# Debian-specific configuration
deb:
  compression: xz
  fields:
    Bugs: https://github.com/algorand/go-algorand/issues

# RPM-specific configuration
rpm:
  group: Applications/Internet
  compression: gzip
  summary: Algorand node software

overrides:
  rpm:
    depends:
      - systemd
      - shadow-utils
      - dnf-automatic
