# nFPM configuration for the algorand-devtools package
# Generates both .deb and .rpm from a single config
# Reference: https://nfpm.goreleaser.com/configuration/
#
# Required environment variables:
#   VERSION             - Package version (e.g., 4.5.0)
#   CHANNEL             - Release channel (stable, beta, nightly, dev)
#   PKG_NAME            - Base package name: "algorand" or "algorand-beta"
#   DEVTOOLS_PKG_NAME   - Devtools package name: "algorand-devtools" or "algorand-devtools-beta"
#   TOOLSDIR            - Directory containing devtools binaries (tools/ subdirectory)

name: ${DEVTOOLS_PKG_NAME}
arch: ${GOARCH}
version: ${VERSION}
platform: linux

maintainer: Algorand developers <dev@algorand.com>
vendor: Algorand Inc.
homepage: https://www.algorand.com
license: AGPL-3.0-or-later
description: |
  Algorand development tools.
  This package provides development and debugging tools for the Algorand blockchain.

# Require the main algorand package at the same version
# Note: top-level uses Debian syntax; RPM syntax is in overrides.rpm.depends
depends:
  - ${PKG_NAME} (>= ${VERSION})

replaces:
  - algorand-devtools
  - algorand-devtools-beta

conflicts:
  - algorand-devtools
  - algorand-devtools-beta

contents:
  # Development tool binaries (expand: true required for env var expansion)
  - src: ${TOOLSDIR}/carpenter
    dst: /usr/bin/carpenter
    expand: true
    file_info:
      mode: 0755

  - src: ${TOOLSDIR}/msgpacktool
    dst: /usr/bin/msgpacktool
    expand: true
    file_info:
      mode: 0755

  - src: ${TOOLSDIR}/tealdbg
    dst: /usr/bin/tealdbg
    expand: true
    file_info:
      mode: 0755

  # License file (rpm only; deb uses the copyright file below)
  - src: COPYING
    dst: /usr/share/licenses/${DEVTOOLS_PKG_NAME}/COPYING
    expand: true
    packager: rpm
    file_info:
      mode: 0644

  # Debian copyright file (deb only, generated at build time)
  - src: .github/packaging/generated/copyright
    dst: /usr/share/doc/${DEVTOOLS_PKG_NAME}/copyright
    expand: true
    packager: deb
    file_info:
      mode: 0644

# RPM-specific configuration
rpm:
  group: Development/Tools
  compression: gzip
  summary: Algorand development tools

overrides:
  rpm:
    depends:
      - ${PKG_NAME} >= ${VERSION}
