#!/usr/bin/expect -f
#exp_internal 1
set err 0
log_user 1

if { [catch {

    source  goalExpectCommon.exp
    set TEST_ALGO_DIR [lindex $argv 0]
    set TEST_DATA_DIR [lindex $argv 1]

    puts "TEST_ALGO_DIR: $TEST_ALGO_DIR"

    spawn cp ../../../../testdata/configs/system-v0.json $TEST_ALGO_DIR/system.json

    # Start node
    ::AlgorandGoal::StartNode $TEST_ALGO_DIR True

    # Restart node
    ::AlgorandGoal::RestartNode $TEST_ALGO_DIR True

    # Stop node
    ::AlgorandGoal::StopNode $TEST_ALGO_DIR True

    puts "Basic Goal Test Successful"

    exit 0
} EXCEPTION] } {
    puts "ERROR in goalNodeStartSystemdTest: $EXCEPTION"
    exit 1
}
