#!/usr/bin/expect -f
#exp_internal 1
set err 0
log_user 1

if { [catch {

    source  goalExpectCommon.exp
    set TEST_ALGO_DIR [lindex $argv 0]
    set TEST_DATA_DIR [lindex $argv 1]

    puts "TEST_ALGO_DIR: $TEST_ALGO_DIR"
    puts "TEST_DATA_DIR: $TEST_DATA_DIR"

    set TIME_STAMP [clock seconds]

    set TEST_ROOT_DIR $TEST_ALGO_DIR/root
    set TEST_PRIMARY_NODE_DIR $TEST_ROOT_DIR/Primary/
    set NETWORK_NAME test_net_expect_$TIME_STAMP
    set NETWORK_TEMPLATE "$TEST_DATA_DIR/nettemplates/TwoNodes50Each.json"

    exec cp $TEST_DATA_DIR/../../gen/devnet/genesis.json $TEST_ALGO_DIR

    # Create network
    ::AlgorandGoal::CreateNetwork $NETWORK_NAME $NETWORK_TEMPLATE $TEST_ALGO_DIR $TEST_ROOT_DIR

    # Start network
    ::AlgorandGoal::StartNetwork $NETWORK_NAME $NETWORK_TEMPLATE $TEST_ALGO_DIR $TEST_ROOT_DIR

    set PRIMARY_NODE_ADDRESS [ ::AlgorandGoal::GetAlgodNetworkAddress $TEST_PRIMARY_NODE_DIR ]
    puts "Primary Node Address: $PRIMARY_NODE_ADDRESS"

    set PRIMARY_WALLET_NAME unencrypted-default-wallet

    # Determine primary account
    set PRIMARY_ACCOUNT_ADDRESS [::AlgorandGoal::GetHighestFundedAccountForWallet $PRIMARY_WALLET_NAME  $TEST_PRIMARY_NODE_DIR]

    # Check the balance of the primary account
    set PRIMARY_ACCOUNT_BALANCE [::AlgorandGoal::GetAccountBalance $PRIMARY_WALLET_NAME $PRIMARY_ACCOUNT_ADDRESS $TEST_PRIMARY_NODE_DIR]
    puts "Primary Account Balance: $PRIMARY_ACCOUNT_BALANCE"

    spawn echo "hello"
    expect {
        timeout { abort "\n Failed to see expected input hello" }
        "^hello*" {close}
    }
    set TEAL_PROGS_DIR $TEST_DATA_DIR/../scripts/e2e_subs/tealprogs

    puts "calling goal app create"
    spawn goal app create --creator $PRIMARY_ACCOUNT_ADDRESS --approval-prog ${TEAL_PROGS_DIR}//loccheck.teal --global-byteslices 0 --global-ints 0 --local-byteslices 1 --local-ints 0 --app-arg "str:hello" -d $TEST_PRIMARY_NODE_DIR --clear-prog \'int 1\'

    spawn goal app create --creator $PRIMARY_ACCOUNT_ADDRESS --approval-prog ${TEAL_PROGS_DIR}/loccheck.teal --global-byteslices 0 --global-ints 0 --local-byteslices 1 --local-ints 0 --app-arg "str:hello" -d $TEST_PRIMARY_NODE_DIR --clear-prog \`int 1\'
    expect {
        timeout { abort "\n Failed to see expected input hello" }
        {Created*} {set APP_ID $expect_out(buffer) }
    }
    puts "App ID $APP_ID"

    # Application call with no args should fail
    puts "calling goal app call with no args"
    spawn goal app call --app-id $APP_ID --from $PRIMARY_ACCOUNT_ADDRESS -w $PRIMARY_WALLET_NAME -d $TEST_PRIMARY_NODE_DIR
    expect {
        timeout { puts timeout; ::AlgorandGoal::Abort  "\n Failed to see expected output" }
        "Couldn't broadcast tx with algod: HTTP 400 Bad Request: TransactionPool.Remember: transaction*" {puts "received expected error"; close}
        eof {puts "did not receive expected error" ; return 1}
        #ignore_errors  true
    }

    # Application call with arg0 == "write" should fail before we opt in
    puts "calling goal app call with account that has not opted in"
    spawn goal app call --app-id $APP_ID --app-arg "str:write" -w $WALLET_1_NAME --from $ACCOUNT_1_ADDRESS -d $TEST_PRIMARY_NODE_DIR
    expect {
        timeout { puts timeout; ::AlgorandGoal::Abort  "\n Failed to see expected output" }
        "Please enter the password for wallet '$WALLET_1_NAME':" {send "$WALLET_1_PASSWORD\r"}
    }
    expect {
        timeout { puts timeout; ::AlgorandGoal::Abort  "\n Failed to see expected output" }
        "*not opted in to app*" {puts "received expected error"; close}
        eof {puts "did not receive expected error" ; return 1}
    }


    # Should succeed to opt in with first arg hello
    puts "opting in account to app"
    spawn goal app optin --app-id $APP_ID --app-arg "str:hello" -w $WALLET_1_NAME --from $ACCOUNT_1_ADDRESS -d $TEST_PRIMARY_NODE_DIR
    expect {
        timeout { puts timeout; ::AlgorandGoal::Abort  "\n Failed to see expected output" }
        "Please enter the password for wallet '$WALLET_1_NAME':" {send "$WALLET_1_PASSWORD\r"}
    }
    expect {
        timeout { puts timeout; ::AlgorandGoal::Abort  "\n Failed to see expected output" }
        "*committed in round*" {puts "optin successful"; close}
        eof {puts "optin failed" ; return 1}
    }

    # Application call with arg0 == "write" should succeed after opt in
    puts "calling goal app call with account that has opted in"
    spawn goal app call --app-id $APP_ID --app-arg "str:write" -w $WALLET_1_NAME --from $ACCOUNT_1_ADDRESS -d $TEST_PRIMARY_NODE_DIR
    expect {
        timeout { puts timeout; ::AlgorandGoal::Abort  "\n Failed to see expected output" }
        "Please enter the password for wallet '$WALLET_1_NAME':" {send "$WALLET_1_PASSWORD\r"}
    }
    expect {
        timeout { puts timeout; ::AlgorandGoal::Abort  "\n Failed to see expected output" }
        "*committed in round*" {puts "app call succeeded"; close}
        eof {puts "app call failed" ; return 1}
    }

    # Check should now succeed with value "bar"
    puts "calling goal app call arg check with account"
    spawn goal app call --app-id $APP_ID --app-arg "str:check" --app-arg "str:bar" -w $WALLET_1_NAME --from $ACCOUNT_1_ADDRESS -d $TEST_PRIMARY_NODE_DIR
    expect {
        timeout { puts timeout; ::AlgorandGoal::Abort  "\n Failed to see expected output" }
        "Please enter the password for wallet '$WALLET_1_NAME':" {send "$WALLET_1_PASSWORD\r"}
    }
    expect {
        timeout { puts timeout; ::AlgorandGoal::Abort  "\n Failed to see expected output" }
        "*committed in round*" {puts "app call succeeded"; close}
        eof {puts "app call failed" ; return 1}
    }

    # Should succeed to close out with first arg hello
    #${gcmd} app closeout --app-id $APPID --from $ACCOUNT --app-arg "str:hello"
    puts "calling goal app close out with first arg hello"
    spawn goal app closeout --app-id $APP_ID --app-arg "str:hello" -w $WALLET_1_NAME --from $ACCOUNT_1_ADDRESS -d $TEST_PRIMARY_NODE_DIR
    expect {
        timeout { puts timeout; ::AlgorandGoal::Abort  "\n Failed to see expected output" }
        "Please enter the password for wallet '$WALLET_1_NAME':" {send "$WALLET_1_PASSWORD\r"}
    }
    expect {
        timeout { puts timeout; ::AlgorandGoal::Abort  "\n Failed to see expected output" }
        "*committed in round*" {puts "app closeout succeeded"; close}
        eof {puts "app closeout failed" ; return 1}
    }

    # Write/opt in in one tx should succeed
    #${gcmd} app optin --app-id $APPID --from $ACCOUNT --app-arg "str:write"
    # Should succeed to opt in with first arg write
    puts "opting in account to app"
    spawn goal app optin --app-id $APP_ID --app-arg "str:write" -w $WALLET_1_NAME --from $ACCOUNT_1_ADDRESS -d $TEST_PRIMARY_NODE_DIR
    expect {
        timeout { puts timeout; ::AlgorandGoal::Abort  "\n Failed to see expected output" }
        "Please enter the password for wallet '$WALLET_1_NAME':" {send "$WALLET_1_PASSWORD\r"}
    }
    expect {
        timeout { puts timeout; ::AlgorandGoal::Abort  "\n Failed to see expected output" }
        "*committed in round*" {puts "optin successful"; close}
        eof {puts "optin failed" ; return 1}
    }

    # Check should still succeed
    #${gcmd} app call --app-id $APPID --app-arg "str:check" --app-arg "str:bar" --from $ACCOUNT
    puts "call app"
    spawn goal app call --app-id $APP_ID --app-arg "str:check" --app-arg "str:bar" -w $WALLET_1_NAME --from $ACCOUNT_1_ADDRESS -d $TEST_PRIMARY_NODE_DIR
    expect {
        timeout { puts timeout; ::AlgorandGoal::Abort  "\n Failed to see expected output" }
        "Please enter the password for wallet '$WALLET_1_NAME':" {send "$WALLET_1_PASSWORD\r"}
    }
    expect {
        timeout { puts timeout; ::AlgorandGoal::Abort  "\n Failed to see expected output" }
        "*committed in round*" {puts "call successful"; close}
        eof {puts "call failed" ; return 1}
    }

    # Delete application should still succeed
    puts "call app delete"
    spawn goal app delete --app-id $APP_ID --app-arg "str:hello" -w $WALLET_1_NAME --from $ACCOUNT_1_ADDRESS -d $TEST_PRIMARY_NODE_DIR
    expect {
        timeout { puts timeout; ::AlgorandGoal::Abort  "\n Failed to see expected output" }
        "Please enter the password for wallet '$WALLET_1_NAME':" {send "$WALLET_1_PASSWORD\r"}
    }
    expect {
        timeout { puts timeout; ::AlgorandGoal::Abort  "\n Failed to see expected output" }
        "*committed in round*" {puts "app delete successful"; close}
        eof {puts "app delete failed" ; return 1}
    }

    # Shutdown the network
    ::AlgorandGoal::StopNetwork $NETWORK_NAME $TEST_ALGO_DIR $TEST_ROOT_DIR

    puts "Goal Stateful Teal test Successful"

    exit 0

} EXCEPTION ] } {
   ::AlgorandGoal::Abort "ERROR in statefulTealCreateAppTest: $EXCEPTION"
}
