// Code generated by gen.go; DO NOT EDIT.

package vpack

// voteValueType enumerates every value-bearing field (full path).
type voteValueType uint8

const (
	credPfVoteValue voteValueType = iota
	rPerVoteValue
	rPropDigVoteValue
	rPropEncdigVoteValue
	rPropOperVoteValue
	rPropOpropVoteValue
	rRndVoteValue
	rSndVoteValue
	rStepVoteValue
	sigP1sVoteValue
	sigP2VoteValue
	sigP2sVoteValue
	sigPVoteValue
	sigPsVoteValue
	sigSVoteValue
)

const (
	msgpFixstrCred   = "\xa4cred"
	msgpFixstrDig    = "\xa3dig"
	msgpFixstrEncdig = "\xa6encdig"
	msgpFixstrOper   = "\xa4oper"
	msgpFixstrOprop  = "\xa5oprop"
	msgpFixstrP      = "\xa1p"
	msgpFixstrP1s    = "\xa3p1s"
	msgpFixstrP2     = "\xa2p2"
	msgpFixstrP2s    = "\xa3p2s"
	msgpFixstrPer    = "\xa3per"
	msgpFixstrPf     = "\xa2pf"
	msgpFixstrProp   = "\xa4prop"
	msgpFixstrPs     = "\xa2ps"
	msgpFixstrR      = "\xa1r"
	msgpFixstrRnd    = "\xa3rnd"
	msgpFixstrS      = "\xa1s"
	msgpFixstrSig    = "\xa3sig"
	msgpFixstrSnd    = "\xa3snd"
	msgpFixstrStep   = "\xa4step"
)
