version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - docnamecheck
    - errortype
    - gosec
    - partitiontest
  settings:
    gosec:
      excludes: [G101, G103, G104, G107, G112, G114, G115, G202, G204, G301, G302, G303, G304, G306, G307, G404]
    custom:
      docnamecheck:
        type: module
        description: "docnamecheck catches doc comments with mismatched function names"
        original-url: "https://github.com/cce/docnamecheck"
        settings:
          include-exported: true
          include-types: true
          include-generated: false
      errortype:
        type: module
        description: "errortype helps prevent subtle bugs in error handling."
        original-url: "https://fillmore-labs.com/errortype"
        settings:
          style-check: false
          deep-is-check: true
          check-is: true
          unchecked-assert: false
          check-unused: true
      partitiontest:
        type: "module"
        description: This custom linter ensures test functions call 'partitiontest.PartitionTest(t)'
  exclusions:
    generated: lax
    rules:
      # be more lenient with test code
      - linters:
          - gosec
        path: _test\.go
      - linters:
          - partitiontest
        path: crypto/secp256k1/secp256_test\.go
issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
severity:
  default: warning
formatters:
  exclusions:
    generated: lax
