version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - gosec
    - partitiontest
  settings:
    gosec:
      # Go 1.22 makes G601 irrelevant
      excludes: [G101, G103, G104, G107, G115, G202, G301, G302, G303, G304, G306, G307, G404, G601]
    custom:
      partitiontest:
        type: "module"
        description: This custom linter checks files that end in '_test.go', specifically functions that start with 'Test' and have testing argument, for a line 'partitiontest.ParitionTest(<testing arg>)'
  exclusions:
    generated: lax
    rules:
      # be more lenient with test code
      - linters:
          - gosec
        path: _test\.go
      - linters:
          - partitiontest
        path: crypto/secp256k1/secp256_test\.go
      # ignore govet false positive fixed in https://github.com/golang/go/issues/45043
      - path: (.+)\.go$
        text: 'sigchanyzer: misuse of unbuffered os.Signal channel as argument to signal.Notify'
      # ignore issues about the way we use _struct fields to define encoding settings
      - path: (.+)\.go$
        text: '`_struct` is unused'

      # Enable some golangci-lint default exception rules:
      # "EXC0001 errcheck: Almost all programs ignore errors on these functions and in most cases it's ok"
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
      # "EXC0005 staticcheck: Developers tend to write in C-style with an explicit 'break' in a 'switch', so it's ok to ignore"
      - path: (.+)\.go$
        text: ineffective break statement. Did you mean to break out of the outer loop
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  # use these new lint checks on code since #2574
  new-from-rev: eb019291beed556ec6ac1ceb4a15114ce4df0c57

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
severity:
  default: warning
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
