version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - gosec
    - partitiontest
  settings:
    gosec:
      excludes: [G101, G103, G104, G107, G115, G202, G301, G302, G303, G304, G306, G307, G404]
    custom:
      partitiontest:
        type: "module"
        description: This custom linter checks files that end in '_test.go', specifically functions that start with 'Test' and have testing argument, for a line 'partitiontest.ParitionTest(<testing arg>)'
  exclusions:
    generated: lax
    rules:
      # be more lenient with test code
      - linters:
          - gosec
        path: _test\.go
      - linters:
          - partitiontest
        path: crypto/secp256k1/secp256_test\.go
issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
severity:
  default: warning
formatters:
  exclusions:
    generated: lax
