tasks:
  - task: docker.Version
    configFilePath: scripts/configure_dev-deps.sh
  - task: shell.docker.Ensure
    image: algorand/go-algorand-ci-linux
    version: '{{ docker.Version.outputs.version }}'
    dockerFilePath: docker/build/cicd.Dockerfile
    dependencies: docker.Version
  - task: docker.Make
    name: build
    docker:
      image: algorand/go-algorand-ci-linux
      version: '{{ docker.Version.outputs.version }}'
      workDir: /go/src/github.com/algorand/go-algorand
    target: ci-build
  - task: docker.Make
    name: fulltest
    docker:
      image: algorand/go-algorand-ci-linux
      version: '{{ docker.Version.outputs.version }}'
      workDir: /go/src/github.com/algorand/go-algorand
    target: fulltest -j4
  - task: docker.Make
    name: shorttest
    docker:
      image: algorand/go-algorand-ci-linux
      version: '{{ docker.Version.outputs.version }}'
      workDir: /go/src/github.com/algorand/go-algorand
    target: shorttest -j4
  - task: docker.Make
    name: integration-test
    docker:
      image: algorand/go-algorand-ci-linux
      version: '{{ docker.Version.outputs.version }}'
      workDir: /go/src/github.com/algorand/go-algorand
    target: ci-integration -j4
  - task: shell.Make
    name: deps
    target: ci-deps 
  - task: shell.Make
    name: build
    target: ci-build
  - task: shell.Make
    name: fulltest
    target: fulltest -j4
  - task: shell.Make
    name: shorttest
    target: shorttest -j3
  - task: shell.Make
    name: integration-test
    target: ci-integration -j4
  - task: shell.Make
    name: archive
    target: archive

jobs:
  # Linux arm64 jobs
  build-linux-arm64:
    configs:
      arch: arm64v8
      docker:
        env:
          - TRAVIS_OS_NAME=${TRAVIS_OS_NAME}
          - TRAVIS_BRANCH=${TRAVIS_BRANCH}
          - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
          - S3_RELEASE_BUCKET=${S3_RELEASE_BUCKET}
    tasks:
      - shell.docker.Ensure
      - docker.Make.build
  test-linux-arm64-fulltest:
    configs:
      arch: arm64v8
      docker:
        env:
          - TRAVIS_OS_NAME=${TRAVIS_OS_NAME}
          - TRAVIS_BRANCH=${TRAVIS_BRANCH}
          - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
          - S3_RELEASE_BUCKET=${S3_RELEASE_BUCKET}
    tasks:
      - shell.docker.Ensure
      - docker.Make.fulltest
  test-linux-arm64-shorttest:
    configs:
      arch: arm64v8
      docker:
        env:
          - TRAVIS_OS_NAME=${TRAVIS_OS_NAME}
          - TRAVIS_BRANCH=${TRAVIS_BRANCH}
          - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
          - S3_RELEASE_BUCKET=${S3_RELEASE_BUCKET}
    tasks:
      - shell.docker.Ensure
      - docker.Make.shorttest
  test-linux-arm64-integration:
    configs:
      arch: arm64v8
      docker:
        env:
          - SHORTTEST=${SHORTTEST}
          - TRAVIS_OS_NAME=${TRAVIS_OS_NAME}
          - TRAVIS_BRANCH=${TRAVIS_BRANCH}
          - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
          - S3_RELEASE_BUCKET=${S3_RELEASE_BUCKET}
    tasks:
      - shell.docker.Ensure
      - docker.Make.integration-test



  # Linux amd64 jobs
  build-linux-amd64:
    configs:
      arch: amd64
      docker:
        env:
          - TRAVIS_OS_NAME=${TRAVIS_OS_NAME}
          - TRAVIS_BRANCH=${TRAVIS_BRANCH}
          - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
          - S3_RELEASE_BUCKET=${S3_RELEASE_BUCKET}
    tasks:
      - shell.docker.Ensure
      - docker.Make.build
  test-linux-amd64-fulltest:
    configs:
      arch: amd64
      docker:
        env:
          - TRAVIS_OS_NAME=${TRAVIS_OS_NAME}
          - TRAVIS_BRANCH=${TRAVIS_BRANCH}
          - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
          - S3_RELEASE_BUCKET=${S3_RELEASE_BUCKET}
    tasks:
      - shell.docker.Ensure
      - docker.Make.fulltest
  test-linux-amd64-shorttest:
    configs:
      arch: amd64
      docker:
        env:
          - TRAVIS_OS_NAME=${TRAVIS_OS_NAME}
          - TRAVIS_BRANCH=${TRAVIS_BRANCH}
          - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
          - S3_RELEASE_BUCKET=${S3_RELEASE_BUCKET}
    tasks:
      - shell.docker.Ensure
      - docker.Make.shorttest
  test-linux-amd64-integration:
    configs:
      arch: amd64
      docker:
        env:
          - SHORTTEST=${SHORTTEST}
          - TRAVIS_OS_NAME=${TRAVIS_OS_NAME}
          - TRAVIS_BRANCH=${TRAVIS_BRANCH}
          - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
          - S3_RELEASE_BUCKET=${S3_RELEASE_BUCKET}
    tasks:
      - shell.docker.Ensure
      - docker.Make.integration-test



  # Local jobs
  build-local:
    tasks:
      - shell.Make.deps
      - shell.Make.build
  test-local-fulltest:
    tasks:
      - shell.Make.deps
      - shell.Make.fulltest
  test-local-shorttest:
    tasks:
      - shell.Make.deps
      - shell.Make.shorttest
  test-local-integration:
    tasks:
      - shell.Make.deps
      - shell.Make.integration-test
  archive-local:
    tasks:
      - shell.Make.deps
      - shell.Make.archive



  # Linux arm jobs
  build-linux-arm:
    configs:
      arch: arm32v6
      target: ci-build
    tasks:
    - docker.Make
  test-linux-arm-shorttest:
    configs:
      arch: arm32v6
      target: shorttest
    tasks:
    - docker.Make
