agents:
  - name: cicd.ubuntu.amd64
    dockerFilePath: docker/build/cicd.ubuntu.Dockerfile
    image: algorand/go-algorand-ci-linux-ubuntu
    version: scripts/configure_dev-deps.sh
    arch: amd64
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
      - ARCH=amd64
  - name: cicd.centos.amd64
    dockerFilePath: docker/build/cicd.centos.Dockerfile
    image: algorand/go-algorand-ci-linux-centos
    version: scripts/configure_dev-deps.sh
    arch: amd64
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
      - ARCH=amd64
  - name: cicd.ubuntu.arm64
    dockerFilePath: docker/build/cicd.ubuntu.Dockerfile
    image: algorand/go-algorand-ci-linux-ubuntu
    version: scripts/configure_dev-deps.sh
    arch: arm64v8
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
      - ARCH=arm64v8
  - name: cicd.centos.arm64
    dockerFilePath: docker/build/cicd.centos.Dockerfile
    image: algorand/go-algorand-ci-linux-centos
    version: scripts/configure_dev-deps.sh
    arch: arm64v8
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
      - ARCH=arm64v8
  - name: docker-ubuntu
    dockerFilePath: docker/build/docker.ubuntu.Dockerfile
    image: algorand/go-algorand-docker-linux-ubuntu
    version: scripts/configure_dev-deps.sh
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

tasks:
  - task: docker.Make
    name: rpm.amd64
    agent: cicd.centos.amd64
    target: mule-package-rpm

  - task: docker.Make
    name: deb.amd64
    agent: cicd.ubuntu.amd64
    target: mule-package-deb
  
  - task: docker.Make
    name: rpm.arm64
    agent: cicd.centos.arm64
    target: mule-package-rpm

  - task: docker.Make
    name: deb.arm64
    agent: cicd.ubuntu.arm64
    target: mule-package-deb

  - task: docker.Make
    name: docker-image
    agent: docker-ubuntu
    target: mule-package-docker

jobs:
  package-linux-amd64:
    tasks:
      - docker.Make.deb.amd64
      - docker.Make.rpm.amd64
  package-linux-arm64:
    tasks:
      - docker.Make.deb.arm64
      - docker.Make.rpm.arm64

  package-docker:
    tasks:
      - docker.Make.docker-image

