tasks:
  - task: docker.Version
    configFilePath: scripts/configure_dev-deps.sh

  - task: shell.docker.Ensure
    name: deploy
    image: algorand/mule-linux-debian
    version: '{{ docker.Version.outputs.version }}'
    dockerFilePath: docker/build/mule.go.debian.Dockerfile
    dependencies: docker.Version

  - task: docker.Make
    name: package-deploy
    docker:
      image: algorand/mule-linux-debian
      version: '{{ docker.Version.outputs.version }}'
      workDir: /projects/go-algorand
      env: [
        AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      ]
    target: mule-deploy WORKDIR=/projects/go-algorand

  - task: shell.Make
    name: generate-releases-page
    target: mule-deploy-generate-releases-page

  - task: s3.BucketCopy
    name: deploy
    bucketSrc: ben-test-2.0.3
    prefixSrc: stable/2.0.5
    bucketDest: algorand-dev-deb-repo
    prefixDest: releases/stable/test

jobs:
  package-deploy:
    configs:
      arch: amd64
    tasks:
      - shell.docker.Ensure.deploy
      - docker.Make.package-deploy

  package-deploy-setup-generate-releases-page:
    tasks:
      - shell.Make.generate-releases-page

  package-deploy-setup-copy:
    tasks:
      - s3.BucketCopy.deploy

