tasks:
  - task: docker.Version
    configFilePath: scripts/configure_dev-deps.sh

  - task: shell.docker.Ensure
    name: docker-ubuntu
    image: algorand/go-algorand-docker-linux-ubuntu
    version: '{{ docker.Version.outputs.version }}'
    dockerFilePath: docker/build/docker.ubuntu.Dockerfile
    dependencies: docker.Version

  - task: shell.docker.Ensure
    name: rpm
    image: algorand/go-algorand-ci-linux-centos
    version: '{{ docker.Version.outputs.version }}'
    dockerFilePath: docker/build/cicd.centos.Dockerfile
    dependencies: docker.Version

  - task: shell.docker.Ensure
    name: deb
    image: algorand/go-algorand-ci-linux-ubuntu
    version: '{{ docker.Version.outputs.version }}'
    dockerFilePath: docker/build/cicd.ubuntu.Dockerfile
    dependencies: docker.Version

  - task: docker.Make
    name: build
    docker:
      image: algorand/go-algorand-ci-linux-centos
      version: '{{ docker.Version.outputs.version }}'
      workDir: /projects/go-algorand
    target: ci-build

  - task: docker.Make
    name: rpm
    docker:
      image: algorand/go-algorand-ci-linux-centos
      version: '{{ docker.Version.outputs.version }}'
      workDir: /projects/go-algorand
    target: package-rpm WORKDIR=/projects/go-algorand

  - task: docker.Make
    name: deb
    docker:
      image: algorand/go-algorand-ci-linux-ubuntu
      version: '{{ docker.Version.outputs.version }}'
      workDir: /projects/go-algorand
    target: package-deb WORKDIR=/projects/go-algorand

  - task: docker.Make
    name: package-sign
    docker:
      image: algorand/go-algorand-ci-linux-ubuntu
      version: '{{ docker.Version.outputs.version }}'
      workDir: /projects/go-algorand
      env: [
        VERSION=2.0.5
      ]
      volumes: [
        $XDG_RUNTIME_DIR/gnupg/S.gpg-agent:/root/.gnupg/S.gpg-agent,
        $HOME/.gnupg/pubring.kbx:/root/.gnupg/pubring.kbx,
        #        $HOME/.gnupg/trustdb.gpg:/root/.gnupg/trustdb.gpg
        #        /var/run/docker.sock:/var/run/docker.sock,
        #        /run/user/1001/gnupg/S.gpg-agent:/root/S.gpg-agent
      ]
    target: package-sign WORKDIR=/projects/go-algorand

  - task: docker.Make
    name: docker-image
    docker:
      image: algorand/go-algorand-docker-linux-ubuntu
      version: '{{ docker.Version.outputs.version }}'
      workDir: /projects/go-algorand
      volumes: [ /var/run/docker.sock:/var/run/docker.sock ]
    target: package-docker WORKDIR=/projects/go-algorand

jobs:
  package:
    configs:
      arch: amd64
    tasks:
      - shell.docker.Ensure.rpm
      - docker.Make.rpm
      - shell.docker.Ensure.deb
      - docker.Make.deb

  package-sign:
    configs:
      arch: amd64
    tasks:
      - shell.docker.Ensure.deb
      - docker.Make.package-sign

  package-docker:
    configs:
      arch: amd64
    tasks:
      - shell.docker.Ensure.docker-ubuntu
      - docker.Make.docker-image

