agents:
  - name: deb
    dockerFilePath: docker/build/cicd.ubuntu.Dockerfile
    image: algorand/cicd-ubuntu
    version: scripts/configure_dev-deps.sh
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
    env:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - NETWORK=$NETWORK
      - VERSION=$VERSION
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker:/root/.docker
    workDir: $HOME/projects/go-algorand

  - name: releases-page
    dockerFilePath: docker/build/releases-page.Dockerfile
    image: algorand/releases-page
    version: scripts/configure_dev-deps.sh
    env:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    workDir: $HOME/projects/go-algorand

  - name: rpm
    dockerFilePath: docker/build/cicd.centos.Dockerfile
    image: algorand/cicd-centos
    version: scripts/configure_dev-deps.sh
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
    env:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - PACKAGES_DIR=$PACKAGES_DIR
      - NO_DEPLOY=$NO_DEPLOY
      - VERSION=$VERSION
    volumes:
      - $XDG_RUNTIME_DIR/gnupg/S.gpg-agent:/root/.gnupg/S.gpg-agent
      - $HOME/.gnupg/pubring.kbx:/root/.gnupg/pubring.kbx
    workDir: $HOME/projects/go-algorand

tasks:
  - task: docker.Make
    name: rpm
    agent: rpm
    target: mule-deploy-rpm

jobs:
  package-deploy:
    tasks:
      - docker.Make.rpm

  package-deploy-deb:
    tasks:
      - docker.Make.deb

  package-deploy-rpm:
    tasks:
      - docker.Make.rpm
