tasks:
  - task: docker.Version
    configFilePath: scripts/configure_dev-deps.sh

  - task: shell.docker.Ensure
    name: rpm
    image: algorand/go-algorand-ci-linux-centos
    version: '{{ docker.Version.outputs.version }}'
    dockerFilePath: docker/build/cicd.centos.Dockerfile
    dependencies: docker.Version

  - task: shell.docker.Ensure
    name: deb
    image: algorand/go-algorand-ci-linux-ubuntu
    version: '{{ docker.Version.outputs.version }}'
    dockerFilePath: docker/build/cicd.ubuntu.Dockerfile
    dependencies: docker.Version

  - task: docker.Make
    name: build
    docker:
      image: algorand/go-algorand-ci-linux-centos
      version: '{{ docker.Version.outputs.version }}'
      workDir: /projects/go-algorand
    target: ci-build

  - task: docker.Make
    name: rpm
    docker:
      image: algorand/go-algorand-ci-linux-centos
      version: '{{ docker.Version.outputs.version }}'
      workDir: /projects/go-algorand
      volumes: [ /home/btoll/go/bin:/projects/go-algorand/go/bin ]
    target: package-rpm

  - task: docker.Make
    name: deb
    docker:
      image: algorand/go-algorand-ci-linux-ubuntu
      version: '{{ docker.Version.outputs.version }}'
      workDir: /projects/go-algorand
      volumes: [ /home/btoll/go/bin:/projects/go-algorand/go/bin ]
    target: package-deb

jobs:
  package:
    configs:
      arch: amd64
      docker:
        env:
          - FOO=foo
    tasks:
      - shell.docker.Ensure.rpm
      - docker.Make.rpm
      - shell.docker.Ensure.deb
      - docker.Make.deb

