agents:
  - name: docker
    dockerFilePath: docker/build/docker.ubuntu.Dockerfile
    image: algorand/docker
    version: scripts/configure_dev-deps.sh
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
    env:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - NETWORK=$NETWORK
      - VERSION=$VERSION
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker:/root/.docker
    workDir: $HOME/projects/go-algorand

  - name: releases-page
    dockerFilePath: docker/build/releases-page.Dockerfile
    image: algorand/releases-page
    version: scripts/configure_dev-deps.sh
    env:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - NETWORK=$NETWORK
      - VERSION=$VERSION
    workDir: $HOME/projects/go-algorand

  - name: deb
    dockerFilePath: docker/build/aptly.Dockerfile
    image: algorand/aptly
    version: scripts/configure_dev-deps.sh
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
    env:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - NETWORK=$NETWORK
      - SNAPSHOT=$SNAPSHOT
      - STAGING=$STAGING
      - VERSION=$VERSION
    volumes:
      - $XDG_RUNTIME_DIR/gnupg/S.gpg-agent:/root/.gnupg/S.gpg-agent
      - $HOME/.gnupg/pubring.kbx:/root/.gnupg/pubring.kbx
    workDir: $HOME/projects/go-algorand

  - name: rpm
    dockerFilePath: docker/build/cicd.centos.Dockerfile
    image: algorand/go-algorand-ci-linux-centos
    version: scripts/configure_dev-deps.sh
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
    env:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - NETWORK=$NETWORK
      - PACKAGES_DIR=$PACKAGES_DIR
      - NO_DEPLOY=$NO_DEPLOY
      - S3_SOURCE=$S3_SOURCE
      - VERSION=$VERSION
    volumes:
      - $XDG_RUNTIME_DIR/gnupg/S.gpg-agent:/root/.gnupg/S.gpg-agent
      - $HOME/.gnupg/pubring.kbx:/root/.gnupg/pubring.kbx
    workDir: $HOME/projects/go-algorand

tasks:
  - task: docker.Make
    name: docker
    agent: docker
    target: mule-docker

  - task: docker.Make
    name: releases-page
    agent: releases-page
    target: mule-releases-page

  - task: docker.Make
    name: deb
    agent: deb
    target: mule-deploy-deb

  - task: docker.Make
    name: rpm
    agent: rpm
    target: mule-deploy-rpm

jobs:
  package-deploy:
    tasks:
      - docker.Make.deb
      - docker.Make.rpm
      - docker.Make.docker
      - docker.Make.releases-page

  package-deploy-deb:
    tasks:
      - docker.Make.deb

  package-deploy-rpm:
    tasks:
      - docker.Make.rpm

  docker-hub:
    tasks:
      - docker.Make.docker

  releases-page:
    tasks:
      - docker.Make.releases-page

