tasks:
  - task: docker.Version
    configFilePath: scripts/configure_dev-deps.sh

  - task: shell.docker.Ensure
    name: docker-mule
    image: algorand/go-algorand-ci-mule-debian
    version: '{{ docker.Version.outputs.version }}'
    dockerFilePath: docker/build/mule.debian.Dockerfile
    dependencies: docker.Version

  - task: docker.Make
    name: package-sign-deb
    docker:
      image: algorand/go-algorand-ci-mule-debian
      version: '{{ docker.Version.outputs.version }}'
      workDir: /projects/go-algorand
      env: [
        VERSION=2.0.5
      ]
      volumes: [
        $XDG_RUNTIME_DIR/gnupg/S.gpg-agent:/root/.gnupg/S.gpg-agent,
        $HOME/.gnupg/pubring.kbx:/root/.gnupg/pubring.kbx
      ]
    target: package-sign-deb WORKDIR=/projects/go-algorand

  - task: docker.Make
    name: package-sign-rpm
    docker:
      image: algorand/go-algorand-ci-mule-debian
      version: '{{ docker.Version.outputs.version }}'
      workDir: /projects/go-algorand
      env: [
        VERSION=2.0.5
      ]
      volumes: [
        $XDG_RUNTIME_DIR/gnupg/S.gpg-agent:/root/.gnupg/S.gpg-agent,
        $HOME/.gnupg/pubring.kbx:/root/.gnupg/pubring.kbx
      ]
    target: package-sign-rpm WORKDIR=/projects/go-algorand

  - task: docker.Make
    name: package-sign-tarball
    docker:
      image: algorand/go-algorand-ci-mule-debian
      version: '{{ docker.Version.outputs.version }}'
      workDir: /projects/go-algorand
      env: [
        VERSION=2.0.5
      ]
      volumes: [
        $XDG_RUNTIME_DIR/gnupg/S.gpg-agent:/root/.gnupg/S.gpg-agent,
        $HOME/.gnupg/pubring.kbx:/root/.gnupg/pubring.kbx
      ]
    target: package-sign-tarball WORKDIR=/projects/go-algorand

jobs:
  package-sign:
    configs:
      arch: amd64
    tasks:
      - shell.docker.Ensure.deb
      - docker.Make.package-sign-deb
      - docker.Make.package-sign-rpm

