agents:
  - name: rpm
    dockerFilePath: docker/build/mule.go.centos.Dockerfile
    image: algorand/mule-linux-centos
    version: scripts/configure_dev-deps.sh
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
    env:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID,
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    volumes:
      - $HOME/packages:/root/packages,
      - $XDG_RUNTIME_DIR/gnupg/S.gpg-agent:/root/.gnupg/S.gpg-agent,
      - $HOME/.gnupg/pubring.kbx:/root/.gnupg/pubring.kbx
    workDir: $HOME/projects/go-algorand

tasks:
  - task: docker.Make
    name: rpm
    agent: rpm
    target: mule-deploy-rpm

  - task: s3.BucketCopy
    name: gnupg
    src: s3://algorand-devops-misc/tools/gnupg2.2.9_centos7_amd64.tar.bz2
    dest: /root

jobs:
  package-deploy:
    tasks:
      - docker.Make.rpm

  package-deploy-setup-gnupg:
    tasks:
      - s3.BucketCopy.gnupg


