tasks:
  - task: docker.Version
    configFilePath: scripts/configure_dev-deps.sh

  - task: shell.docker.Ensure
    name: docker-ubuntu
    image: algorand/go-algorand-docker-linux-ubuntu
    version: '{{ docker.Version.outputs.version }}'
    dockerFilePath: docker/build/docker.ubuntu.Dockerfile
    dependencies: docker.Version

  - task: shell.docker.Ensure
    name: rpm
    image: algorand/go-algorand-ci-linux-centos
    version: '{{ docker.Version.outputs.version }}'
    dockerFilePath: docker/build/cicd.centos.Dockerfile
    dependencies: docker.Version

  - task: docker.Make
    name: package-sign
    docker:
      image: algorand/go-algorand-ci-linux-ubuntu
      version: '{{ docker.Version.outputs.version }}'
      workDir: /projects/go-algorand
      env: [
        VERSION=2.0.5
      ]
      volumes: [
        $XDG_RUNTIME_DIR/gnupg/S.gpg-agent:/root/.gnupg/S.gpg-agent,
        $HOME/.gnupg/pubring.kbx:/root/.gnupg/pubring.kbx
      ]
    target: package-sign WORKDIR=/projects/go-algorand

jobs:
  package-sign:
    configs:
      arch: amd64
    tasks:
      - shell.docker.Ensure.deb
      - docker.Make.package-sign

