agents:
  - name: deb
    dockerFilePath: docker/build/cicd.ubuntu.Dockerfile
    image: algorand/go-algorand-ci-linux-ubuntu
    version: scripts/configure_dev-deps.sh
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
    workDir: $HOME/projects/go-algorand

  - name: rpm
    dockerFilePath: docker/build/cicd.centos.Dockerfile
    image: algorand/go-algorand-ci-linux-centos
    version: scripts/configure_dev-deps.sh
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
    workDir: $HOME/projects/go-algorand

  - name: docker
    dockerFilePath: docker/build/docker.ubuntu.Dockerfile
    image: algorand/go-algorand-docker-linux-ubuntu
    version: scripts/configure_dev-deps.sh
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    workDir: $HOME/projects/go-algorand

tasks:
  - task: docker.Make
    name: rpm
    agent: rpm
    target: mule-package-rpm

  - task: docker.Make
    name: deb
    agent: deb
    target: mule-package-deb

  - task: docker.Make
    name: docker
    agent: docker
    target: mule-package-docker

jobs:
  package:
    tasks:
      - docker.Make.deb
      - docker.Make.rpm
      - docker.Make.docker

  package-deb:
    tasks:
      - docker.Make.deb

  package-rpm:
    tasks:
      - docker.Make.rpm

  package-docker:
    tasks:
      - docker.Make.docker

