tasks:
  - task: docker.Version
    configFilePath: scripts/configure_dev-deps.sh

  - task: shell.docker.Ensure
    name: docker-ubuntu
    image: algorand/go-algorand-docker-linux-ubuntu
    version: '{{ docker.Version.outputs.version }}'
    dockerFilePath: docker/build/docker.ubuntu.Dockerfile
    dependencies: docker.Version

  - task: shell.docker.Ensure
    name: rpm
    image: algorand/go-algorand-ci-linux-centos
    version: '{{ docker.Version.outputs.version }}'
    dockerFilePath: docker/build/cicd.centos.Dockerfile
    dependencies: docker.Version

  - task: shell.docker.Ensure
    name: deb
    image: algorand/go-algorand-ci-linux-ubuntu
    version: '{{ docker.Version.outputs.version }}'
    dockerFilePath: docker/build/cicd.ubuntu.Dockerfile
    dependencies: docker.Version

  - task: docker.Make
    name: build
    docker:
      image: algorand/go-algorand-ci-linux-centos
      version: '{{ docker.Version.outputs.version }}'
      workDir: /projects/go-algorand
    target: ci-build

  - task: docker.Make
    name: rpm
    docker:
      image: algorand/go-algorand-ci-linux-centos
      version: '{{ docker.Version.outputs.version }}'
      workDir: /projects/go-algorand
    target: mule-package-rpm WORKDIR=/projects/go-algorand

  - task: docker.Make
    name: deb
    docker:
      image: algorand/go-algorand-ci-linux-ubuntu
      version: '{{ docker.Version.outputs.version }}'
      workDir: /projects/go-algorand
    target: mule-package-deb WORKDIR=/projects/go-algorand

  - task: docker.Make
    name: docker-image
    docker:
      image: algorand/go-algorand-docker-linux-ubuntu
      version: '{{ docker.Version.outputs.version }}'
      workDir: /projects/go-algorand
      volumes: [ /var/run/docker.sock:/var/run/docker.sock ]
    target: mule-package-docker WORKDIR=/projects/go-algorand

jobs:
  package:
    configs:
      arch: amd64
    tasks:
      - shell.docker.Ensure.rpm
      - docker.Make.rpm
      - shell.docker.Ensure.deb
      - docker.Make.deb

  package-docker:
    configs:
      arch: amd64
    tasks:
      - shell.docker.Ensure.docker-ubuntu
      - docker.Make.docker-image

