agents:
  - name: deb
    dockerFilePath: docker/build/mule.go.debian.Dockerfile
    image: algorand/mule-linux-debian
    version: scripts/configure_dev-deps.sh
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
    env:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - BRANCH=$BRANCH
      - CHANNEL=$CHANNEL
      - NETWORK=$NETWORK
      - SHA=$SHA
      - VERSION=$VERSION
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    workDir: $HOME/projects/go-algorand

tasks:
  - task: docker.Make
    name: package-test-deb
    agent: deb
    target: mule-test-deb

  - task: docker.Make
    name: package-test-rpm
    agent: deb
    target: mule-test-rpm

jobs:
  package-test:
    tasks:
      - docker.Make.package-test-deb
      - docker.Make.package-test-rpm

  package-test-deb:
    tasks:
      - docker.Make.package-test-deb

  package-test-rpm:
    tasks:
      - docker.Make.package-test-rpm

