def REGION = "us-west-1"
def AMI = "ami-0dd655843c87b6930"
def TYPE = "t2.2xlarge"

pipeline {
    parameters {
        string defaultValue: 'master', description: 'Branch name or tag name.', name: 'branch', trim: true
    }

    environment {
        AWS_ACCESS_KEY_ID = credentials("prod-s3-aws-access-key-id")
        AWS_SECRET_ACCESS_KEY = credentials("prod-s3-aws-secret-access-key")
    }

    agent {
        dockerfile {
            filename 'scripts/release/common/docker/setup.Dockerfile'
            args '-u root'
        }
    }

    stages {
        stage("create ec2 instance") {
            steps {
                sh script: "scripts/release/common/create.sh ${REGION} ${AMI} ${TYPE}"
            }
        }

        stage("setup") {
            steps {
                sh script: "scripts/release/test/stage/setup/run.sh ${params.branch}"
            }
        }

        stage("test") {
            steps {
                sh script: "scripts/release/test/stage/test/run.sh ${params.branch}"
            }
        }

        stage("delete ec2 instance") {
            steps {
                sh script: "scripts/release/common/delete.sh ${REGION}"
            }
        }
    }
}

