set export
set shell := ["zsh", "-cu"]

NETWORKS := `echo $HOME` + "/networks"
NAME := "niftynetwork"
TEMP_NETWORK := NETWORKS + "/" + NAME
GO_ALGORAND := "../../.."
NODE_TEMPLATE := GO_ALGORAND + "/test/testdata/nettemplates/OneNodeFuture.json"
ALGORAND_DATA := TEMP_NETWORK + "/Primary"
BOXES_TEAL := "boxes.teal"

# --- SUMMARY --- #

# list all available commands
default:
    just --list

# echo all variables
@echo:
    echo NETWORKS: $NETWORKS
    echo NAME: $NAME
    echo TEMP_NETWORK: $TEMP_NETWORK
    echo GO_ALGORAND: $GO_ALGORAND
    echo NODE_TEMPLATE: $NODE_TEMPLATE
    echo ALGORAND_DATA: $ALGORAND_DATA
    echo BOXES_TEAL: $BOXES_TEAL

# --- COMPOUND --- #

# create and then start (error if already created)
@create_and_start: create start status
    sleep 5
    just status

# create an app and then fund it
@app-create_fund: app-create last-app-fund 


# stop and tear down the node network
@stop_and_nuke: stop nuke


# --- PRE-REQUISITES --- #

# calculate an app's address using the python SDK
app-address *ARGS:
    #!/usr/bin/env python3
    from algosdk import logic
    print(logic.get_application_address({{ ARGS }}))

# --- NETWORKS / NODE --- #

# create a private network with one node (error if already created)
@create:
	mkdir -p $NETWORKS
	goal network create -n $NAME -r $TEMP_NETWORK -t $NODE_TEMPLATE

# start a the network (error if already running or not created)
@start:
	goal node start

# status of network node
@status:
	goal node status && echo "running" || echo "not running"

# stop the running node (error if not running)
@stop:
	goal node stop

# remove the node's data from the file system
@nuke:
    echo "deleting $TEMP_NETWORK"
    rm -rf $TEMP_NETWORK

# --- ACCOUNTS --- #

# list all associated accounts
@list:
	goal account list

# funding account's address
@funder:
    just list | awk '{print $2}'
    
# provide information about a given account
@info $ACCOUNT=`just funder`:
    goal account info --address {{ACCOUNT}}

# provide an account's balance
@balance $ACCOUNT=`just funder`:
    goal account balance --address {{ACCOUNT}}

# funder's most recently created app-id
@last-app-id:
    just info | grep ID | tail -n 1 | cut -d "," -f1 | awk '{print $2}'

# the account address of the funders most recently created app-id
@last-app-address:
    just app-address `just last-app-id`

# --- Applications --- #

# print out the boxes teal program
@boxes_teal:
    cat $BOXES_TEAL

# shortcut for the approval and clear program `goal app create` params
@programs:
    echo "--approval-prog $BOXES_TEAL --clear-prog clear.teal"

# shortcut for the storage params of `goal app create`
@app-vars:
    echo "--global-byteslices 0 --global-ints 0 --local-byteslices 0 --local-ints 0"

# create an app funded by funder account
@app-create:
    goal app create --creator `just funder` `just programs` `just app-vars`


# --- CLERK --- #

# fund the most recently created app
@last-app-fund $AMOUNT=`echo 1000000`:
    goal clerk send --from `just funder` --to `just last-app-address`  --amount {{AMOUNT}}

