pipeline {
    environment {
        AWS_ACCESS_KEY_ID = credentials("aws-access-key-id")
        AWS_SECRET_ACCESS_KEY = credentials("aws-secret-access-key")
    }

    agent any

    stages {
        stage("create ec2 instance") {
            steps {
                sh script: "scripts/buildhost/start_ec2_instance.sh"
            }
        }

        stage("setup ec2 instance") {
            steps {
                sh 'scp -o StrictHostKeyChecking=no -i BuilderInstanceKey.pem -r scripts/release/ ubuntu@$(cat $PWD/scripts/buildhost/tmp/instance):~/'
                sh 'ssh -i BuilderInstanceKey.pem -A ubuntu@$(cat $PWD/scripts/buildhost/tmp/instance) "bash release/setup.sh"'
                sh 'aws s3 cp s3://algorand-devops-misc/tools/gnupg2.2.9_centos7_amd64.tar.bz2 $HOME/docker_test_resources'
            }
        }

        stage("release ec2 instance") {
            steps {
                sh 'ssh -i BuilderInstanceKey.pem -A ubuntu@$(cat $PWD/scripts/buildhost/tmp/instance) "bash release/release.sh"'
            }
        }

        stage("delete ec2 instance") {
            steps {
                sh script: "scripts/buildhost/shutdown_ec2_instance.sh"
            }
        }
    }
}

