// generated by dbgen; DO NOT EDIT

package agreement

import "database/sql"

func agreeInstallDatabase(tx *sql.Tx) error {
	statement := `create table Service (
       data blob --*  msgpack encoding of Service
);
`
	_, err := tx.Exec(statement)
	if err != nil {
		return err
	}

	return nil
}
