package: public
generate:
  echo-server: true
  embedded-spec: true
output-options:
  include-tags:
  - nonparticipating
  - public
  exclude-tags:
  - private
  - common
  - participating
  - data
  - experimental
  skip-prune: true
  user-templates:
    echo/echo-register.tmpl: ./templates/echo/echo-register.tmpl
additional-imports:
  - alias: "."
    package: "github.com/algorand/go-algorand/daemon/algod/api/server/v2/generated/model"
output: ./server/v2/generated/nonparticipating/public/routes.go
