package: experimental
generate:
  echo-server: true
  embedded-spec: true
output-options:
  include-tags:
  - experimental
  - public
  exclude-tags:
  - common
  - private
  - participating
  - nonparticipating
  - data
  type-mappings:
    integer: uint64
  skip-prune: true
additional-imports:
  - alias: "."
    package: "github.com/algorand/go-algorand/daemon/algod/api/server/v2/generated/model"
output: ./server/v2/generated/experimental/routes.go
