name: 'Setup Build Environment'
description: 'Set up Go, libsodium, and build dependencies for release builds'
inputs:
  cache-prefix:
    description: 'Cache prefix for Go caching'
    required: false
    default: 'release'
runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: ./.github/actions/setup-go
      with:
        cache-prefix: ${{ inputs.cache-prefix }}

    - name: Cache libsodium
      uses: actions/cache@v4
      with:
        path: crypto/libs
        key: libsodium-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('crypto/libsodium-fork/**') }}

    - name: Install build dependencies (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake libtool

    - name: Install build dependencies (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        # Homebrew packages needed for libsodium build
        brew install autoconf automake libtool

    - name: Build libsodium
      shell: bash
      run: make libsodium
