package: private
generate:
  echo-server: true
  embedded-spec: true
output-options:
  include-tags:
  - participating
  - private
  exclude-tags:
  - public
  - nonparticipating
  - data
  - common
  skip-prune: true
  user-templates:
    echo/echo-register.tmpl: ./templates/echo/echo-register.tmpl
additional-imports:
  - alias: "."
    package: "github.com/algorand/go-algorand/daemon/algod/api/server/v2/generated/model"
output: ./server/v2/generated/participating/private/routes.go
