name: "Pay (full)"
genesis_accounts: 10000
genesis_account_balance: 1000000000000
tx_per_block: 5000

# transaction distribution
tx_pay_fraction: 1.0

# payment config
pay_acct_create_fraction: 0.02
pay_xfer_fraction: 0.98

# asset config must be 1.0
asset_create_fraction: 1.0
