name: "Boxes Optins Small"
tx_per_block: 100

tx_app_fraction: 1

# payment config
pay_acct_create_fraction: 0.02
pay_xfer_fraction: 0.98

# asset config
tx_asset_create_fraction: 1.0

# app kind config
app_boxes_fraction: 1.0

# app boxes config
app_boxes_create_fraction: 0.01
app_boxes_optin_fraction: 0.89
app_boxes_call_fraction: 0.1
