name: 'Setup Go with Multi-Module Caching'
description: 'Set up Go with caching for all go.sum files in the repository'
runs:
  using: 'composite'
  steps:
    - name: Get Go version
      id: go_version
      run: echo "GO_VERSION=$(./scripts/get_golang_version.sh)" >> $GITHUB_ENV
      shell: bash
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
        cache-dependency-path: |
          go.sum
          cmd/partitiontest_linter/go.sum
          tools/block-generator/go.sum
          tools/x-repo-types/go.sum