name: 'Setup Go with caching'
description: 'Set up Go with mod and build caching'
runs:
  using: 'composite'
  steps:
    - name: Get Go version
      id: go_version
      run: echo "GO_VERSION=$(./scripts/get_golang_version.sh)" >> $GITHUB_ENV
      shell: bash
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: false
    # following advice from https://danp.net/posts/github-actions-go-cache/
    - name: Set cache date and paths
      shell: bash
      run: |
        echo "GO_CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        echo "GOMODCACHE=$(go env GOMODCACHE)" >> $GITHUB_ENV
        echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_ENV
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ${{ env.GOMODCACHE }}
        key: ${{ runner.os }}-go-mod-${{ github.ref_name }}-${{ hashFiles('**/go.sum') }}-${{ env.GO_CACHE_DATE }}
        restore-keys: |
          ${{ runner.os }}-go-mod-${{ github.ref_name }}-${{ hashFiles('**/go.sum') }}-
          ${{ runner.os }}-go-mod-${{ github.ref_name }}-
          ${{ runner.os }}-go-mod-master-
          ${{ runner.os }}-go-mod-
    - name: Cache Go build cache
      uses: actions/cache@v4
      with:
        path: ${{ env.GOCACHE }}
        key: ${{ runner.os }}-go-build-${{ github.ref_name }}-${{ hashFiles('**/go.sum') }}-${{ env.GO_CACHE_DATE }}
        restore-keys: |
          ${{ runner.os }}-go-build-${{ github.ref_name }}-${{ hashFiles('**/go.sum') }}-
          ${{ runner.os }}-go-build-${{ github.ref_name }}-
          ${{ runner.os }}-go-build-master-
          ${{ runner.os }}-go-build-
    - name: Download Go modules
      shell: bash
      run: go mod download
