name: 'Save Partition Timing Data'
description: 'Save test timing data to cache for future partition optimization'
inputs:
  test-type:
    description: 'Test type (test, integration, e2e_expect)'
    required: true
  platform:
    description: 'Platform (ubuntu-24.04, macos-14, etc.)'
    required: true
  partition-total:
    description: 'Expected total number of partitions'
    required: true
  run-id:
    description: 'GitHub run ID for unique cache key'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Validate partition total
      shell: bash
      run: |
        # Validate partition total matches actual number of partition directories
        TEST_RESULTS_DIR="$HOME/test_results/${{ inputs.platform }}_${{ inputs.test-type }}"
        if [ -d "$TEST_RESULTS_DIR" ]; then
          ACTUAL_PARTITIONS=$(find "$TEST_RESULTS_DIR" -maxdepth 1 -type d -name '[0-9]*' | wc -l | tr -d ' ')
          EXPECTED_PARTITIONS="${{ inputs.partition-total }}"
          if [ "$ACTUAL_PARTITIONS" != "$EXPECTED_PARTITIONS" ]; then
            echo "ERROR: Expected $EXPECTED_PARTITIONS partitions but found $ACTUAL_PARTITIONS"
            echo "This indicates a configuration mismatch in ci-pr.yml"
            exit 1
          fi
          echo "Validated $ACTUAL_PARTITIONS partitions match expected count"
        else
          echo "ERROR: No test results directory found at $TEST_RESULTS_DIR"
          exit 1
        fi
    - name: Prepare timing data directory
      shell: bash
      run: |
        mkdir -p results/${{ inputs.platform }}_${{ inputs.test-type }}
        # Copy all testresults.json files from the test run
        TEST_RESULTS_DIR="$HOME/test_results/${{ inputs.platform }}_${{ inputs.test-type }}"
        if [ -d "$TEST_RESULTS_DIR" ]; then
          # Find and copy all testresults.json files, preserving structure
          find "$TEST_RESULTS_DIR" -name "testresults.json" -type f | while read file; do
            # Get relative path from test_results
            rel_path="${file#$HOME/test_results/}"
            target_dir="results/$(dirname "$rel_path")"
            mkdir -p "$target_dir"
            cp "$file" "$target_dir/"
          done
          echo "Copied timing data to results/ directory"
          echo "Timing data files:"
          find results -name "testresults.json" -type f
          echo "Total timing entries:"
          find results -name "testresults.json" -exec cat {} \; | grep -c '"Action":"pass"' || echo "0"
        else
          echo "No test results found at $TEST_RESULTS_DIR"
        fi
    - name: Save timing data to cache
      uses: actions/cache/save@v4
      if: always()
      with:
        path: results
        # Use run-id to create unique key, but restore-keys will find the latest
        key: test-timing-${{ inputs.test-type }}-${{ inputs.platform }}-${{ inputs.partition-total }}-${{ github.ref_name }}-${{ inputs.run-id }}
