#!/usr/bin/env bash
# shellcheck disable=2045

set -ex

if [ -z "$BRANCH" ] || [ -z "$CHANNEL" ] || [ -z "$SHA" ] || [ -z "$VERSION" ] || [ -z "$NETWORK" ]
then
    echo "[ERROR] $0 -b $BRANCH -c $CHANNEL -h $SHA -n $NETWORK -r $VERSION"
    exit 1
fi

if [ "$PKG_TYPE" == "deb" ]
then
    for deb in $(ls "./tmp/node_pkgs/$OS_TYPE/$ARCH_TYPE"/*"$VERSION"*.deb); do
        if [[ ! "$deb" =~ devtools ]]; then
            dpkg -i "$deb"
        fi
    done
#else
#    for rpm in $(ls "./tmp/node_pkgs/$OS_TYPE/$ARCH_TYPE"/*"$VERSION"*.rpm); do
#        if [[ ! "$rpm" =~ devtools ]]; then
#            yum install "$rpm" -y
#        fi
#    done
fi

for test in $(ls ./scripts/release/mule/test/tests/*.sh)
do
    bash "$test"
done

