#!/usr/bin/env bash

set -e

PKG_NAME=@PKG_NAME@
INDEXER=algorand-indexer

if [ "$1" != install ] || [ "$PKG_NAME" == $INDEXER ]
then
    exit 0
fi

if dpkg-query --list 'algorand*' &> /dev/null
then
    PKG_INFO=$(dpkg-query --show --showformat='${Package} ${Status}\n' 'algorand*' | grep "install ok installed")
    INSTALLED_PKG=$(grep -v $INDEXER <<< "$PKG_INFO" | awk '{print $1}')

    if [ -n "$INSTALLED_PKG" ]
    then
        echo -e "\nAlgorand does not currently support multi-distribution installations!\n\
To install this package, it is necessary to first remove the \`$INSTALLED_PKG\` package:\n\n\
sudo apt-get remove $INSTALLED_PKG\n\
sudo apt-get install $PKG_NAME\n"
        exit 1
    fi
fi

