#!/bin/bash

function runCheckGenesis() {
    echo >&2 "Checking to see if 'gen' needs to be run..."
    ./scripts/check_genesis.sh
}

runCheckGenesis
if [ $? -ne 0 ]; then exit 1; fi

echo "pre-commit checks passed."
