#!/usr/bin/expect -f
set err 0
log_user 1

#ensure that telemetry is not disabled by default.
#export ALGOTEST=0


if { [catch {
    source algodExpectCommon.exp

    set TEST_ALGO_DIR [lindex $argv 0]

    puts "TEST_ALGO_DIR: $TEST_ALGO_DIR"

    set TIME_STAMP [clock seconds]

    exec mkdir $TEST_ALGO_DIR
    ::Algod::ReadTelemetry $TEST_ALGO_DIR
    exec rm -d -r $TEST_ALGO_DIR

    puts "Basic Algod Test Successful"
    exit 0

} EXCEPTION ] } {
   puts "ERROR in algod test: $EXCEPTION"
   exec rm -d -r $TEST_ALGO_DIR
}