name: "Build Windows"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-windows:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Windows build environment
        uses: ./.github/actions/setup-windows-build
      - name: Build
        run: |
          export ALGORAND_DEADLOCK=enable
          export SKIP_GO_INSTALLATION=True
          scripts/travis/build_test.sh
      - name: Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST --data-urlencode "payload={\"text\": \"Build windows failed. ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \"}" $SLACK_WEBHOOK_URL
        if: ${{ failure() && (contains(github.ref_name, 'rel/nightly') || contains(github.ref_name, 'rel/beta') || contains(github.ref_name, 'rel/stable') || contains(github.ref_name, 'master')) }}
