name: container

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - feature/*

jobs:
  build-and-push:
    name: Build and Push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.3

      - name: Generate Container Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ github.repository_owner }}/algod
          tags: |
            type=sha,format=long,prefix=
            type=ref,event=branch

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            SHA=${{ github.sha }}
            URL=${{ github.server_url }}/${{ github.repository }}.git
            BRANCH=${{ github.ref_name }}

  # TODO: uncomment when https://github.com/docker/hub-tool/issues/172 is complete
  # update-repo-description:
  #   name: Update DockerHub Repository Description
  #   runs-on: ubuntu-latest
  #   if: github.ref == format('refs/heads/{0}', 'master')
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3.5.3

  #     - name: Update DockerHub Repository Description
  #       uses: peter-evans/dockerhub-description@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #         repository: ${{ github.repository_owner }}/algod
  #         readme-filepath: ./docker/README.md
