name: "Benchmark workflow"
on:
  push:
    branches:
      - master
  pull_request:
# For demonstration purposes, allow paton to run on all PRs.
#    branches:
#      - master
permissions:
  contents: write
  deployments: write
jobs:
  paton:
    name: paton
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - run: go install golang.org/x/perf/cmd/benchstat@latest
      - run: sudo apt-get update
      - run: sudo apt-get -y -q install jc jq
      - run: ./scripts/configure_dev.sh
        shell: bash
      - run: ./scripts/buildtools/install_buildtools.sh
        shell: bash
      - run: ./scripts/travis/before_build.sh # Installs libsodium.
        shell: bash
      - name: Run benchmark
        run: ./scripts/paton.sh --test-cmd "-run XXX -benchtime 5s -bench BenchmarkControl ./data/transactions/logic"
        shell: bash
      - name: Push benchmark result to gh-pages branch
        if: github.event_name == 'push'
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: 'customSmallerIsBetter'
          output-file-path: /tmp/benchstat_time_jq.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
      - name: Evaluate benchmark on PR branch
        if: github.event.pull_request
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: 'customSmallerIsBetter'
          output-file-path: /tmp/benchstat_time_jq.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alert-threshold: '10%'
          comment-on-alert: true
 #     - name: Slack Notification
 #       env:
 #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
 #       run: |
 #         curl -X POST --data-urlencode "payload={\"text\": \"Benchmark workflow failed. ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \"}" $SLACK_WEBHOOK
  #      if: ${{ failure() && (contains(github.ref_name, 'rel/nightly') || contains(github.ref_name, 'rel/beta') || contains(github.ref_name, 'rel/stable') || contains(github.ref_name, 'master')) }}
