name: "paton benchmark"
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  paton-benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Restore libsodium from cache
        id: cache-libsodium
        uses: actions/cache@v3
        with:
          path: crypto/libs
          key: libsodium-fork-v1-${{ runner.os }}-${{ hashFiles('crypto/libsodium-fork/**') }}
      - run: go install golang.org/x/perf/cmd/benchstat@latest
      - run: sudo apt-get update
      - run: sudo apt-get -y -q install jq python3-pip
      - run: pip3 install jc # Use pip to install jc because aptitude is stale (https://repology.org/project/jc/versions).
      - run: ./scripts/configure_dev.sh
        shell: bash
      - run: ./scripts/buildtools/install_buildtools.sh
        shell: bash
      - run: ./scripts/travis/before_build.sh # Installs libsodium.
        shell: bash
      - name: Run benchmark
        run: ./scripts/paton.sh --alert-threshold-pct 10 --test-cmd "-run XXX -benchtime 5s -bench BenchmarkControl ./data/transactions/logic"
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: alerting_benchmarks.json
          path: /tmp/alerting_benchmarks.json
      - run: echo ${{ github.event.number }} > /tmp/pr_number.txt
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: pr_number.txt
          path: /tmp/pr_number.txt
 #     - name: Slack Notification
 #       env:
 #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
 #       run: |
 #         curl -X POST --data-urlencode "payload={\"text\": \"Benchmark workflow failed. ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \"}" $SLACK_WEBHOOK
  #      if: ${{ failure() && (contains(github.ref_name, 'rel/nightly') || contains(github.ref_name, 'rel/beta') || contains(github.ref_name, 'rel/stable') || contains(github.ref_name, 'master')) }}
