# Test tools directories that have their own go.mod files, and
# otherwise wouldn't get tested along with the main go-algorand build.
name: Test tools modules
on:
  push:
    branches:
      - master
    paths:
      - 'tools/block-generator/**'
      - 'tools/x-repo-types/**'
  pull_request:

jobs:
  tools_test:
    name: Test tools modules
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Cache libsodium
        uses: actions/cache@v4
        with:
          path: crypto/libs
          key: libsodium-ubuntu-latest-${{ hashFiles('crypto/libsodium-fork/**') }}
      # move go out of the way temporarily to avoid "go list ./..." from installing modules
      - name: Make libsodium.a
        run: sudo mv /usr/bin/go /usr/bin/go.bak && make libsodium && sudo mv /usr/bin/go.bak /usr/bin/go
      - name: Add bin to PATH
        run: |
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          echo "$RUNNER_WORKSPACE/$(basename $GITHUB_REPOSITORY)/bin" >> $GITHUB_PATH
      - name: Set up Go
        uses: ./.github/actions/setup-go
      - name: Test tools/block-generator
        run: |
          cd tools/block-generator
          go test -v ./...
      - name: Test tools/x-repo-types
        run: |
          cd tools/x-repo-types
          go test -v ./...
